import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import AuthProvider from "../context/AuthProvider";
import { LeftSidebar } from "@/components/LeftSidebar/LeftSidebar";
import { RightSidebar } from "@/components/RightSidebar/RightSidebar";
import { BottomNav } from "@/components/BottomNavbar/BottomNavbar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex flex-col min-h-screen bg-black text-white">
            <div className="flex flex-1 justify-center">
              <div className="flex w-full max-w-7xl">
                <LeftSidebar />
                <main className="flex-1 border-x border-gray-800 min-h-screen">
                  {children}
                </main>
                <RightSidebar />
              </div>
            </div>
            <BottomNav />
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
